services:
  # Base de données SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong@Passw0rd' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  # Service d'initialisation de la base de données
  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./scripts:/scripts
    networks:
      - backend-network
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      bash -c "
      echo 'Attente de la base de données...'
      sleep 10
      echo 'Création de la base de données UserServiceDB...'
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'YourStrong@Passw0rd' -C -Q 'IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = ''UserServiceDB'') CREATE DATABASE UserServiceDB' || echo 'Erreur lors de la création'
      echo 'Vérification de la base de données...'
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'YourStrong@Passw0rd' -C -Q 'SELECT name FROM sys.databases WHERE name = ''UserServiceDB'''
      echo 'Initialisation terminée!'
      "
    restart: "no"

  # Service utilisateur
  userservice:
    build:
      context: ./service/UserService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=UserServiceDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
    networks:
      - backend-network
    ports:
      - "5001:80"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "echo ok"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # API Gateway
  apigateway:
    build:
      context: ./service/ApiGateway
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Services__UserService__BaseUrl=http://userservice:80
    depends_on:
      userservice:
        condition: service_healthy
    networks:
      - backend-network
      - frontend-network
    ports:
      - "5000:80"
    restart: on-failure

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - apigateway
    networks:
      - frontend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  sqlserver_data: